var categories = [
  { id: "BT", name: "Bàn thờ" },
  { id: "CH", name: "Ghế" },
  { id: "DE", name: "Dép" },
  { id: "DT", name: "Điện thoại" },
  { id: "FAN", name: "Quát máy" },
  { id: "GI", name: "Giày" },
  { id: "HP", name: "Headphone" },
  { id: "KB", name: "Bàn phím" },
  { id: "LT", name: "Laptop" },
  { id: "MDH", name: "Máy điều hòa" },
  { id: "MT", name: "Máy tính casio" },
  { id: "NM", name: "Nệm" },
  { id: "PC", name: "Máy tính để bàn" },
  { id: "PET", name: "Thú cưng" },
  { id: "QA", name: "Quần áo" },
  { id: "RA", name: "Rau củ" },
  { id: "TA", name: "Tả" },
  { id: "TB", name: "Bàn" },
  { id: "TV", name: "Tivi" },
  { id: "XD", name: "Xe đạp" },
  { id: "XH", name: "Xe hơi" },
  { id: "XM", name: "Xe máy" },
];
export default categories;
